FROM node:20 AS builder

WORKDIR /app

RUN corepack enable && corepack prepare yarn@4.9.1 --activate

COPY package.json yarn.lock .yarnrc.yml turbo.json ./
COPY packages/shared ./packages/shared
COPY apps/server ./apps/server

RUN yarn install

RUN yarn workspace shared build && yarn workspace server build

EXPOSE 3000

CMD ["yarn", "workspace", "server", "start"]